

  NumSortModes = 10;

{ Sort commands }
  cmSortName          = 13001;
  cmSortLongName      = 13002;
  cmSortExt           = 13003;
  cmSortLongExt       = 13004;
  cmSortSize          = 13005;
  cmSortDate          = 13006;
  cmSortCrDate        = 13007;
  cmSortLADate        = 13008;
  cmSortDIZ           = 13009;
  cmSortType          = 13060;
  cmSortUnsorted      = 13000;

{ Panel sort mode }
  psmName      = 1;
  psmLongName  = 2;
  psmExtension = 3;
  psmLongExt   = 4;
  psmSize      = 5;
  psmTime      = 6;
  psmCrTime    = 7;
  psmLATime    = 8;
  psmDIZ       = 9;
  psmUnsorted  = 0;
  psmOrdered   = 60;
