

  NumSortModes = 8;

{ Sort commands }
  cmSortName          = 13001;
  cmSortExt           = 13002;
  cmSortSize          = 13003;
  cmSortDate          = 13004;
  cmSortCrDate        = 13005;
  cmSortLADate        = 13006;
  cmSortDIZ           = 13007;
  cmSortType          = 13060;
  cmSortUnsorted      = 13000;

{ Panel sort mode }
  psmLongName  = 1;
  psmLongExt   = 2;
  psmSize      = 3;
  psmTime      = 4;
  psmCrTime    = 5;
  psmLATime    = 6;
  psmDIZ       = 7;
  psmUnsorted  = 0;
  psmOrdered   = 60;
